- name: easyTravel recovery action
  hosts: all
  tasks:
    - name: Open
      debug:
        msg: "easyTravel app problem detected, trying to recover!"
      when: status == "OPEN"
    - name: Resolved
      debug:
        msg: "easyTravel app recovered"
      when: status == "RESOLVED"
    - name: Check the date on the server.
      command: date