- name: easyTravel recovery action
  hosts: all
  tasks:
    - name: easyTravel bad
      debug:
        msg: "easyTravel app problem detected, trying to recover!"
      when: state == "OPEN"
    - name: easyTravel good
      debug:
        msg: "easyTravel app recovered"
      when: state == "RESOLVED"
    - name: Check the date on the server.
      command: date